title: AXE
email: info@axerunners.com
description: Decentralized X11-based cryptocurrency
url: ""
author: AXErunners
lang: en-US
icon: fa-times

facebook_url: https://www.facebook.com/axe137
github_url: https://github.com/AXErunners
linkedin_url: https://www.linkedin.com/company/axerunners/
slack_url: https://axe-slack.herokuapp.com
twitter_url: https://twitter.com/axerunners

markdown: kramdown
sass:
sass_dir: _sass

plugins:
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-mentions

jekyll-mentions:
    base_url: https://github.com

exclude: [
   "manual.md",
   "Gemfile",
   "node_modules",
   "gulpfile.js",
   "package.json",
   "_site",
   "src",
   "vendor",
   "CNAME",
   "LICENSE.md",
   "maintenance.md",
   "Rakefile"
 ]
