title: AXErunners
email: info@axerunners.com
description: AXE is a decentralized X11-based cryptocurrency
baseurl: ""
url: https://www.axerunners.com
author: charlie137

icon: fa-times

facebook_url: https://www.facebook.com/axe137
github_url: https://github.com/AXErunners
#gitlab_url:
#googleplus_url:
#instagram_url:
linkedin_url: https://www.linkedin.com/company/axerunners/
#pinterest_url:
slack_url: https://axe-slack.herokuapp.com
twitter_url: https://twitter.com/axerunners

markdown: kramdown
sass:
sass_dir: _sass

plugins:
  - jekyll-gist

exclude: [manual.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
