# Site Settings
title: AXErunners
email: none
description: >
  AXE is a decentralized X-11 based cryptocurrency.
baseurl: ""
url: "http://localhost:4000"
twitter_username: none
github_username:  AXErunners
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
