#!/usr/bin/env bash
set -e
bundle exec jekyll build --verbose
bundle exec htmlproofer ./_site --http-status-ignore "999" --url-swap "https?\:\/\/(127\.0\.0\.1\:4000|localhost\:4000|axerunners\.github.io):" --only-4xx --allow-hash-href --empty-alt-ignore --url-ignore "/wallet-generator,https://www.crunchbase.com/organization/axerunners"
